### ISSUE TITLE
error in python auto_reply_msg.py

### ISSUE THREAD

**Issue by shreesha345** [fmirani/whatsapp_bot#1]
input -------------------------------------------------------------------------------
` python auto_reply_msg.py --message "An apple fell from the tree and "`

output -------------------------------------------------
`2021-05-11 10:43:57.648082: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2021-05-11 10:43:57.676772: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "auto_reply_msg.py", line 74, in <module>
    print(fire.Fire(interact_model))
  File "D:\gpt_2\packages\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\gpt_2\packages\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "D:\gpt_2\packages\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "auto_reply_msg.py", line 26, in interact_model
    enc = encoder.get_encoder(models_name)
TypeError: get_encoder() missing 1 required positional argument: 'models_dir'`

**Comment by shreesha345** [comment]
i am having an issue when i run this one i get the error and i am using in a  env   please help me out..
